# I use high ports to avoid easy conflicts with other
# projects when running this docker-compose.
services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres_monorepo_template
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monorepo_template
    ports:
      - "54320:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
    driver: local
    name: monorepo_template_postgres_data
